Update 0026_CheckIn.txt
yveshanoulle/CoachRetreat pull request #3
Opened 2017-12-28 19:15 UTC by irenedoan

2017-12-28 19:59 UTC, yveshanoulle requested changes
hi Irene,
I prefer not to have url's in the book, I have a file at the end for all resources. will you add the book link there?

2017-12-28 23:47 UTC, irenedoan commented
Sure, i'll do it tomorrow...
Good night

Le 28 déc. 2017 20:59, "Yves Hanoulle" <notifications@github.com> a écrit :

> *@yveshanoulle* requested changes on this pull request.
>
> hi Irene,
> I prefer not to have url's in the book, I have a file at the end for all
> resources. will you add the book link there?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yveshanoulle/CoachRetreat/pull/3#pullrequestreview-85875996>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQfNGlfOoErzoJdDBPbU5LNUEIKkZFsnks5tE_MjgaJpZM4ROlAc>
> .
>

2017-12-29 08:38 UTC, irenedoan commented
I moved the url from chapters files to 'Resources.txt"

2017-12-29 09:51 UTC, yveshanoulle approved these changes

2017-12-29 09:52 UTC, merged